name: Build system on Debian 12 AMD64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/gershwin-os/builder-amd64:main
      options: >-
        --privileged
        --name debian
      ports:
        - 8080:8080
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build system on Debian 12 AMD64
        run: |
          make install
        continue-on-error: false
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gershwin-system-amd64-main
          path: /tmp/system.txz
